#pragma once
#include <allegro5/allegro5.h>

namespace gameconfig {

	extern ALLEGRO_COLOR SOLID_BACKGROUND_COLOR_0;
	extern ALLEGRO_COLOR SOLID_BACKGROUND_COLOR_1;
	extern ALLEGRO_COLOR SOLID_BACKGROUND_COLOR_2;
	extern ALLEGRO_COLOR SOLID_BACKGROUND_COLOR_3;
	extern ALLEGRO_COLOR SOLID_TEXT_COLOR_NORMAL;
	extern ALLEGRO_COLOR SOLID_TEXT_COLOR_ALT;
	extern ALLEGRO_COLOR SOLID_TEXT_COLOR_OK;
	extern ALLEGRO_COLOR SOLID_TEXT_COLOR_WARN;
	extern ALLEGRO_COLOR SOLID_TEXT_COLOR_ERROR;
	extern ALLEGRO_COLOR TRANSPARENT_BACKGROUND_COLOR;
	extern ALLEGRO_COLOR TEXT_COLOR;
	extern ALLEGRO_COLOR ALT_TEXT_COLOR;

};

