#pragma once
#include <allegro5/allegro5.h>

namespace gameconfig {

	extern ALLEGRO_COLOR SOLID_BACKGROUND_COLOR_0;
	extern ALLEGRO_COLOR SOLID_BACKGROUND_COLOR_1;
	extern ALLEGRO_COLOR SOLID_BACKGROUND_COLOR_2;
	extern ALLEGRO_COLOR SOLID_BACKGROUND_COLOR_3;
	extern ALLEGRO_COLOR SOLID_TEXT_COLOR_NORMAL;
	extern ALLEGRO_COLOR SOLID_TEXT_COLOR_ALT;
	extern ALLEGRO_COLOR SOLID_TEXT_COLOR_OK;
	extern ALLEGRO_COLOR SOLID_TEXT_COLOR_WARN;
	extern ALLEGRO_COLOR SOLID_TEXT_COLOR_ERROR;
	extern ALLEGRO_COLOR TRANSPARENT_BACKGROUND_COLOR;
	extern ALLEGRO_COLOR TEXT_COLOR;
	extern ALLEGRO_COLOR ALT_TEXT_COLOR;

	extern ALLEGRO_COLOR PLAYER_MENU_SEMI_TRANSPARENT_MENU_COLOR_0;
	extern ALLEGRO_COLOR PLAYER_MENU_SEMI_TRANSPARENT_MENU_COLOR_1;
	extern ALLEGRO_COLOR PLAYER_MENU_SEMI_TRANSPARENT_MENU_COLOR_2;

	extern ALLEGRO_COLOR PLAYER_MENU_PROGBAR_BACK_COLOR_0;
	extern ALLEGRO_COLOR PLAYER_MENU_PROGBAR_FILL_COLOR_0;
	extern ALLEGRO_COLOR PLAYER_MENU_PROGBAR_BACK_COLOR_1;
	extern ALLEGRO_COLOR PLAYER_MENU_PROGBAR_FILL_COLOR_1;

	extern ALLEGRO_COLOR PLAYER_MENU_SEMI_TRANSPARENT_MENU_COLOR_0;
	extern ALLEGRO_COLOR PLAYER_MENU_SEMI_TRANSPARENT_TEXT_COLOR_0;
	extern ALLEGRO_COLOR PLAYER_MENU_SEMI_TRANSPARENT_TEXT_COLOR_1;

	extern ALLEGRO_COLOR PLAYER_MENU_CONSUMABLES_HOTBAR_COLOR;
	extern ALLEGRO_COLOR PLAYER_MENU_USABLES_HOTBAR_COLOR;
	extern ALLEGRO_COLOR PLAYER_MENU_PLACEABLES_HOTBAR_COLOR;


	extern int GUI_DEFAULT_LINE_HEIGHT;
	extern int GUI_DEFAULT_SLOT_SIZE;
	extern int GUI_DEFAULT_TEXT_SIZE;
	extern float GUI_SCALE;

	float GetSlotSize();
	int GetTextSize();
	float GetLineHeight();

	int GetTileSize();

};

